model: timm
backbone: ViT-B-16
dataset: objaverse
matcher: mast3r

hydra:
  run:
    dir: outputs/${model}/${matcher}/${backbone}/${dataset}

  sweep:
    dir: checkpoints
    subdir: ${backbone}

evaluation_methods:
  - semantic_transfer
  - tracking
  - pose