model: timm
backbone: ViT-B-16
dataset: scannetpp
matcher: vggt

hydra:
  run:
    dir: outputs/${model}/${matcher}/${backbone}/${dataset}

  sweep:
    dir: checkpoints
    subdir: ${backbone}

# 평가 방법 지정 (리스트로 여러 개 지정 가능)
evaluation_methods:
  - semantic_transfer
  - tracking
  # - pose  # 필요한 경우 추가